### ISSUE TITLE
UIAutomationCore.dll crash

### ISSUE THREAD

**Issue by EricStancliff** [samhocevar/portable-file-dialogs#51]
Apologies in advance for the vagueness of the issue, I'm not entirely sure what's going wrong - in fact maybe this is the wrong medium for this.  I continually get a crash in UIAutomationCore.dll seemingly randomly and intermittently seconds or minutes AFTER the file dialog is closed successfully.  This crash ONLY occurs if I use a file open dialog (that DLL isn't even loaded prior to the first call to open).  I've attached screenshots of my call stack and my usage of pfd.  I'm on Windows10 Enterprise version 20H2 build 19042.685.

Any guidance you could provide would be much appreciated!! Thanks!!
![UsageContext](https://user-images.githubusercontent.com/25473977/102661269-1f144080-4142-11eb-9ccf-0a4960962a80.PNG)
![BaseClass](https://user-images.githubusercontent.com/25473977/102661271-20456d80-4142-11eb-9d7a-5e78fdc1d52c.PNG)
![CallStack](https://user-images.githubusercontent.com/25473977/102661272-20456d80-4142-11eb-9ab0-b639176ac39a.PNG)
![CallToOpen](https://user-images.githubusercontent.com/25473977/102661273-20456d80-4142-11eb-9bbb-add822f8a62f.PNG)
![OpenDerivedClass](https://user-images.githubusercontent.com/25473977/102661274-20de0400-4142-11eb-9589-04b792daf8ce.PNG)

**Comment by samhocevar** [comment]
Since the crash happens after some random time, I suggest trying to comment out the `FreeLibrary()` call in `internal::platform::dll::~dll`. Let me know if that changes anything.

Otherwise, can you maybe provide more information about the crash itself? Is it an unhandled exception, or an invalid memory access?

**Comment by samhocevar** [comment]
Another possible cause is shell extensions that get loaded by `GetOpenFileNameW`. People seem to complain about them [here](https://stackoverflow.com/q/38362399/111461) or [here](https://stackoverflow.com/q/93154/111461). Do you have extensions such as TortoiseGit installed maybe?

If you add a debugger breakpoint on `get_open_file_name()` and resume execution, you should see a bunch of DLLs loaded by Visual Studio at that moment. It could be helpful to get a list of these DLLs. Thanks in advance!

**Comment by EricStancliff** [comment]
@samhocevar The crash still occurs when I comment out the FreeLibrary() call.  Here are the details:

![disassembly](https://user-images.githubusercontent.com/25473977/102698811-d02fdf00-4205-11eb-9b26-aade1f250b9d.PNG)
Exception thrown at 0x00007FFFF538BB30 (UIAutomationCore.dll) in BMx.exe: 0xC0000005: Access violation reading location 0x00007FFFF52321A8.

**Comment by EricStancliff** [comment]
After the get_open_file_name() call, everything below com was loaded (sorted by order):
![modules](https://user-images.githubusercontent.com/25473977/102698878-4fbdae00-4206-11eb-81fd-624c0f7166c0.PNG)

**Comment by EricStancliff** [comment]
I don't have TortoiseGit, I do have Git Bash installed though.

**Comment by EricStancliff** [comment]
@samhocevar I was able to recreate the crash with this minimal program.
`
#include <iostream>
#include <string>
#include <vector>
#include "portable-file-dialogs.h"

class PathResult
{
public:
	PathResult() = default;
	virtual ~PathResult() = default;
	virtual bool isReady() = 0;
	virtual std::string selection() = 0;
};

class PFD_OpenFileSingle : public PathResult
{
public:
    PFD_OpenFileSingle(std::string const& title,
        std::string const& initial_path,
        const std::vector<std::string>& filters = { "All Files", "*" },
        pfd::opt opt = pfd::opt::none) : _m(title, initial_path, filters, opt) {}
    ~PFD_OpenFileSingle() = default;

    virtual bool isReady() override
    {
        return _m.ready(0);
    }
    virtual std::string selection() override
    {
        auto res = _m.result();
        if (res.empty())
            return "";
        else
            return res.at(0);
    }

private:
    pfd::open_file _m;

};

std::shared_ptr<PathResult> pickSingleFile(const std::string& title, const std::string& defaultPath = "",
    const std::vector<std::string>& filters = { "AllFiles", "*" })
{
    return std::make_shared<PFD_OpenFileSingle>(title, defaultPath, filters, pfd::opt::none);
}

int main(int argc, char* argv[])
{
	while (true)
	{
		std::cout << "Press enter to open dialog." << std::endl;
		while (std::cin.get() != '\n');
		auto fileDialog = pickSingleFile("Test File");
		while (!fileDialog->isReady());
		auto result = fileDialog->selection();
		std::cout << "Picked " << result << std::endl;
	}

	return 0;
}
`

**Comment by EricStancliff** [comment]
I run, pick one file and let sit for a few minutes and it crashes every time.  But only in x64, x86 seems to not crash.

**Comment by EricStancliff** [comment]
Update:  The following code crashes when MULTI is defined:
```
#include <iostream>
#include <string>
#include <vector>
#include <Windows.h>
#include <locale>
#include <codecvt>
#include <future>

std::string openFile(const char* name)
{
    OPENFILENAME ofn;       // common dialog box structure
    wchar_t szFile[260];       // buffer for file name
    HANDLE hf;              // file handle

    // Initialize OPENFILENAME
    ZeroMemory(&ofn, sizeof(ofn));
    ofn.lStructSize = sizeof(ofn);
    ofn.hwndOwner = NULL;
    ofn.lpstrFile = szFile;
    // Set lpstrFile[0] to '\0' so that GetOpenFileName does not 
    // use the contents of szFile to initialize itself.
    ofn.lpstrFile[0] = '\0';
    ofn.nMaxFile = sizeof(szFile);
    ofn.lpstrFilter = L"All\0*.*\0Text\0*.TXT\0";
    ofn.nFilterIndex = 1;
    ofn.lpstrFileTitle = NULL;
    ofn.nMaxFileTitle = 0;
    ofn.lpstrInitialDir = NULL;
    ofn.Flags = OFN_PATHMUSTEXIST | OFN_FILEMUSTEXIST;

    // Display the Open dialog box. 

    if (GetOpenFileName(&ofn) == TRUE)
        hf = CreateFile(ofn.lpstrFile,
            GENERIC_READ,
            0,
            (LPSECURITY_ATTRIBUTES)NULL,
            OPEN_EXISTING,
            FILE_ATTRIBUTE_NORMAL,
            (HANDLE)NULL);

    std::wstring fileName(szFile);
    //setup converter
    using convert_type = std::codecvt_utf8<wchar_t>;
    std::wstring_convert<convert_type, wchar_t> converter;

    //use converter (.to_bytes: wstr->str, .from_bytes: str->wstr)
    std::string converted_str = converter.to_bytes(fileName);
    return converted_str;
}

#define MULTI
int main(int argc, char* argv[])
{
	while (true)
	{
		std::cout << "Press enter to open dialog." << std::endl;
		while (std::cin.get() != '\n');
#ifdef MULTI
        auto result = std::async(std::launch::async, &openFile, "Test");
        auto string = result.get();
#else
        auto string = openFile("Test");
#endif
		std::cout << "Picked " << string << std::endl;
	}

	return 0;
}
```

**Comment by EricStancliff** [comment]
So basically I think it's a personal problem because I don't see anything about it being illegal to launch a common dialog in another thread.  I've had multiple colleagues try and mine is the only one that is crashing.  Probably need to burn my laptop or quit my job.

**Comment by EricStancliff** [comment]
Ok!  So last update.  It appears that if I wrap any dialog work in 
```
    CoInitializeEx(NULL, COINIT_MULTITHREADED);
    GetOpenFileNameA(&ofn);  //for example
    CoUninitialize();

```
the crash goes away.  So my question is, is the multithreaded model the more appropriate model to use since we're doing all of our UI work in a new thread?  The documentation around the STA/MTA threading models is ambiguous at best.  Will defer to the experts here @samhocevar .

Thanks in advance and sorry for the info blast!!

**Comment by samhocevar** [comment]
Well it looks like you did all the hard investigation work! Thanks a lot, I will definitely apply that fix.

One last thing: does `COINIT_APARTMENTTHREADED` fix the problem, too? I am under the impression that this would be enough because all calls are made from the same thread, even if not the main thread.

**Comment by samhocevar** [comment]
I have already pushed a change to Git that uses `COINIT_APARTMENTTHREADED` because that’s the value that was already used for the folder selection dialog. I will switch to `COINIT_MULTITHREADED` if necessary.

**Comment by EricStancliff** [comment]
The issue still happens with COINIT_APARTMENTTHREADED, but not with COINIT_MULTITHREADED.  I believe COINIT_APARTMENTTHREADED is the default.  The call that breaks it seems to be coming from a different windows spawned thread.  My concern is that nobody else seems to be having this issue so I'm skeptical of its validity, but for the life of me I can't figure out what's different about my machine.  I do see this warning in my debugger output in VS:

mincore\com\oleaut32\dispatch\ups.cpp(2122)\OLEAUT32.dll!00007FF8F56E95F6: (caller: 00007FF8F56E8A09) ReturnHr(1) tid(56e8) 8002801D Library not registered.

And then later this:

onecore\com\combase\dcomrem\resolver.cxx(2283)\combase.dll!00007FF8F5A15CDE: (caller: 00007FF8F5AC7BFA) ReturnHr(2) tid(59e4) 80070005 Access is denied.

But I'm unsure if it's related.

**Comment by EricStancliff** [comment]
By the way, I've sheared down my test program to the below:
```
#include <iostream>
#include <string>
#include <vector>
#include <future>

#include <Windows.h>

std::string openFile()
{
    char szFile[260];
    memset(szFile, 0, sizeof(szFile));

    OPENFILENAMEA ofn;
    memset(&ofn, 0, sizeof(ofn));

    ofn.lStructSize = sizeof(ofn);
    ofn.hwndOwner = NULL;
    ofn.lpstrFile = szFile;
    ofn.lpstrFile[0] = '\0';
    ofn.nMaxFile = sizeof(szFile);
    ofn.lpstrFilter = "All\0*.*\0Text\0*.TXT\0";
    ofn.nFilterIndex = 1;
    ofn.lpstrFileTitle = NULL;
    ofn.nMaxFileTitle = 0;
    ofn.lpstrInitialDir = NULL;
    ofn.Flags = OFN_PATHMUSTEXIST | OFN_FILEMUSTEXIST;

    CoInitializeEx(NULL, COINIT_APARTMENTTHREADED);
    GetOpenFileNameA(&ofn);
    CoUninitialize();

    return std::string(szFile);
}

int main(int argc, char* argv[])
{
	while (true)
	{
		std::cout << "Press enter to open dialog." << std::endl;
		while (std::cin.get() != '\n');
        auto result = std::async(std::launch::async, &openFile);
        auto string = result.get();
		std::cout << "Picked " << string << std::endl;
	}
	return 0;
}
```

**Comment by EricStancliff** [comment]
Update - Had a coworker able to recreate the crash finally!  He saw it crash 4 or 5 times and made the change to COINIT_MULTITHREADED and so far that seems to have solved it for him as well.

**Comment by samhocevar** [comment]
Same here, I was finally able to reproduce the bug. And `COINIT_MULTITHREADED` fixes it for me, too.

I have spent an awful lot of time trying to find the actual culprit and there appears to be no documentation for `UIAutomation.dll` and the `ReleaseProvider` function or the `EventMap` class, so I think I’m going to give up and just apply the workaround for now. Thanks again for reporting and investigating the problem.

**Comment by afedorov3** [comment]
COINIT_MULTITHREADED seems to break async kill.
Actual dialog window is being created in a different thread than dialog caller, so enum_windows_callback filter windows by the wrong TID.
![Untitled](https://github.com/user-attachments/assets/dd8201fa-fd44-4012-8d36-493b2ec8376a)
